version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3333:3333
    command: "npm start"
    depends_on: 
     - db
    networks:
      - api
  db:
    image: postgres
    restart: always
    ports: 
     - 5432:5432
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
    networks: 
     - api
networks:
  api: 
    driver: bridge
