version: '3'

services:
  api:
    image: node:fermium-alpine
    depends_on:
      - postgres
    ports:
      - 3333:3333
    restart: "on-failure"
    volumes:
      - ./:/server
    working_dir: /server
    networks:
      - instagram
    command: "npm run dev"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    networks:
      - instagram

networks:
  instagram: null
